"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['space_shooter.py']
DATA_FILES = ['./images/alien.png']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES, options=dict(
        py2app=dict(bdist_base=str(Path(getcwd()).parent) + '/build',
                    dist_dir=str(Path(getcwd()).parent) + '/dist')
    setup_requires=['py2app'],
)
setup(app=['<your_code.py>'],
      options=dict(py2app=dict(bdist_base=str(Path(getcwd()).parent)
      + '/build', dist_dir=str(Path(getcwd()).parent) + '/dist')))